# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: JoyoungKyu
title: web developer
email: dudrb0106@naver.com
# email_title: Email (Email title override)
phone: 010-2733-6914
# phone_title: Phone (Phone title override)
website: interk0736@gmail.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  JoYoungKyu
youtube_username: JoYoungKyu

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/JoYoungKyu.jpg)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: unmanned drone
        link:
        link_text:
        additional_links:
          - title:
            icon:
            url:
          - title:
            icon:
            url:
        quote: >
          production the unmanned drone
        description: | # this will include new lines to allow paragraphs
          Assembly unmanned drone for Arduino part, codiong software program in Arduino and test flying
  - title: Experience
    layout: list
    content:
      - layout: right
        title:
        sub_title:
        caption:
        link:
        quote: >
          
        description:
          
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Bucheon University
        sub_title: lego Ev3 coding
        caption: 2021 - 2021
        quote: >
          assembly The lego and coding the program
        description: |
          I built a conveyor machine with Legos and coded a program to place the items in different positions by color.
      - layout: top-left
        title: Bucheon University
        sub_title: produce kakao chatbot
        caption: 2021 - 2021
        quote: >
          coding the chatbot
        description: | # this will include new lines to allow paragraphs
          Using the Kakao Chatbot, we rewrote the COVID-19 confirmed case and the health center chatbot manual.
  - title: A Little More About Me
    layout: text
    content: 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
